------------------------------------------------
--------------- TB_MEM 관련 테이블 ---------------
------------------------------------------------

CREATE TABLE TB_MEM (
    NO NUMBER PRIMARY KEY,
    MEM_ID VARCHAR2(30) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(10) DEFAULT 'ROLE_USER',
    MEM_NM VARCHAR2(15) NOT NULL,
    PHONE VARCHAR2(13),
    EMAIL VARCHAR2(100),
    ADDR VARCHAR2(100),
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
    ENROLL_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN TB_MEM.NO IS '회원번호';
COMMENT ON COLUMN TB_MEM.MEM_ID IS '회원아이디';
COMMENT ON COLUMN TB_MEM.PASSWORD IS '회원비밀번호';
COMMENT ON COLUMN TB_MEM.ROLE IS '회원타입';
COMMENT ON COLUMN TB_MEM.MEM_NM IS '회원명';
COMMENT ON COLUMN TB_MEM.PHONE IS '전화번호';
COMMENT ON COLUMN TB_MEM.EMAIL IS '이메일';
COMMENT ON COLUMN TB_MEM.ADDR IS '주소';
COMMENT ON COLUMN TB_MEM.STATUS IS '상태값(Y/N)';
COMMENT ON COLUMN TB_MEM.ENROLL_DATE IS '회원가입일';

CREATE SEQUENCE SEQ_UNO;

INSERT INTO TB_MEM (NO, MEM_ID, PASSWORD, ROLE, MEM_NM, PHONE, EMAIL, ADDR,STATUS, ENROLL_DATE) 
        VALUES(SEQ_UNO.NEXTVAL, 'admin', '1234', 'ROLE_ADMIN', '관리자', '010-4179-4341', 'admin@iei.or.kr', '서울시 강남구 역삼동', DEFAULT, DEFAULT);

SELECT * FROM TB_MEM WHERE MEM_ID='admin' AND STATUS='Y';

-- 멤버 조회
-- SELECT * FROM TB_MEM WHERE MEM_ID=? AND STATUS='Y'

-- 멤버 추가
-- INSERT INTO TB_MEM VALUES(SEQ_UNO.NEXTVAL,?,?,DEFAULT,?,?,?,?,DEFAULT,DEFAULT)

-- 멤버 수정               
-- UPDATE TB_MEM SET MEM_NM=?,PHONE=?,EMAIL=?,ADDR=? WHERE NO=?

-- 멤버 패스워드 변경
-- UPDATE TB_MEM SET PASSWORD=? WHERE NO=?

-- 멤버 삭제
-- UPDATE TB_MEM SET STATUS=? WHERE NO=?